title: We shall overcomb
hero_image: images/banner.png
description: we-shall-overcomb description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-2, programming-2, phys-comp-0, manufacture-0, community-1
interests: "jokes/pranks, photography"
technologies: "html/css"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Find an image
  - title: Edit the hair
  - title: Add the images
  - title: Add a slider
  - title: "Challenge: Change the height"
