---
title: Hair today, gone tomorrow
hero_image: images/banner.png
description: Give people funny hairstyles by creating a web app with JavaScript
theme: green
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 2, design-2, programming-2, phys-comp-0, manufacture-0, community-1
interests: humour, photography
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Find an image
- title: Edit the hair
- title: Add the images
- title: Add a slider
- title: 'Challenge: change the height'
- title: Change the position
  completion: internal
- title: 'Challenge: rotate the hair'
